<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="ATMECSINLT-1155" failures="2" tests="7" name="open browser" time="26.264" errors="0" timestamp="2022-07-29T10:46:29 GMT+05:30">
  <testcase classname="pages.LoginPage" name="chromeTest" time="4.292"/>
  <testcase classname="pages.LoginPage" name="firefoxTest" time="4.301"/>
  <testcase classname="pages.LoginPage" name="dataProvider" time="3.575"/>
  <testcase classname="pages.LoginPage" name="dataProvider" time="3.44"/>
  <testcase classname="pages.LoginPage" name="dataProvider" time="8.494"/>
  <testcase classname="pages.LoginPage" name="dataProvider" time="1.768">
    <failure type="java.lang.AssertionError" message="expected [https://www.saucedemo.com/] but found [https://www.saucedemo.com/inventory.html]">
      <![CDATA[java.lang.AssertionError: expected [https://www.saucedemo.com/] but found [https://www.saucedemo.com/inventory.html]
at pages.LoginPage.dataProvider(LoginPage.java:53)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- dataProvider -->
  <testcase classname="pages.LoginPage" name="dataProvider" time="17.633">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at common.ScreenShort.onTestFailure(ScreenShort.java:14)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- dataProvider -->
</testsuite> <!-- open browser -->
